FROM ubuntu:noble

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Madrid

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Update and install all languages + tools
RUN apt-get update && apt-get install -y \
    bash-completion man nano curl wget gnupg software-properties-common \
    ghc cabal-install \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN mkdir /1_odds
WORKDIR /1_odds
COPY . .

ENV DEBIAN_FRONTEND=

RUN echo "alias ls='ls --color'" >> /root/.bashrc \
    && echo "source /etc/bash_completion" >> /root/.bashrc


